show databases;
use customer_behavior ;
-- Q1. what is the total revenue generated by male vs female customrs?
select gender , sum(purchase_amount) as revenue from customer 
group by gender;

-- Q2. which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
 where discount_applied = 'Yes' and 
 purchase_amount >= (select avg(purchase_amount) from customer);
 
-- Q3. which are the top 5 prodcuts with highest average review rating?
select item_purchased, round(Avg(review_rating),2) from customer 
group by item_purchased order by Avg(review_rating) desc limit 5;

-- Q4. compare average purchase amount between standard and express shipping ?
select shipping_type, round(avg(purchase_amount),2) from customer
 where shipping_type in ('Standard', 'Express')
 group by shipping_type;
 
 -- Q5. Do subscribed customer spend more ? compare average spend and total revenue between
 -- subscribed and non-subscripted?
 Select subscription_status,count(customer_id), round(Avg(purchase_amount),2) as average_spend,
 round(Sum(purchase_amount),2) as total_revenue from customer 
 group by subscription_status;
 
 -- Q6. which 5 products have the highest percentage of purchases wiht dicount applied?
 select item_purchased , 
 Round(100 * Sum(case when discount_applied = 'Yes' then 1 else 0 end) /count(*),2) as discount_rate
 from customer group by item_purchased order by discount_rate desc limit 5;
 
 -- Q7.Segment customer into new, return , loyal based on their total number
 -- of previous purchases and show the count of each segment ?
 with customer_type as 
 (select customer_id,previous_purchases , case when previous_purchases = 1 then 'New'
 when previous_purchases between 2 and 10 then 'Returning'
 else 'Loyal' end as customer_segment from customer )
 select customer_segment, count(*) as "Number of customers" from customer_type group by customer_segment;
 
 -- Q8. what are the top 3 most purchased product whithin each category ?
 
 with item_counts as (
 select category, item_purchased, count(customer_id) as Total_orders,
 Row_number() over (partition by category order by count(customer_id) Desc)as item_rank
 from customer group by category, item_purchased )
 Select item_rank, category, item_purchased, Total_orders from item_counts where item_rank <= 3;
 
 -- Q9: Are customers who are repeat buyers (more than 5 previous purchases) are likely to subscribe ?
 
 Select subscription_status, count(customer_id) as Repeat_buyers from customer 
 where previous_purchases > 5 group by subscription_status;
 
 -- Q10. What is revenue contriubtion of each group ?
 select age_group, sum(purchase_amount) as revenue from customer
 group by age_group;